Game_store_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from games.views import IndexView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('catalog/', include('games.urls', namespace='games')),
    path('admin/', admin.site.urls),

    path('api/v1/', include('api.urls', namespace='api')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

api/urls.py
from django.urls import path, include
from api.views import GameListAPIView

from rest_framework import routers

app_name = 'api'


urlpatterns = [
    path('game_list/', GameListAPIView.as_view(), name='get_games'),
]

games/urls.py
from django.urls import path

from games.views import GameView, GameListView, ModalGameView
from games.scrapping import parsing


app_name = 'games'
urlpatterns = [
    path('', GameListView.as_view(), name='catalog'),
    path('dump_games/', parsing),

    path('modal-game/<slug:game_slug>',ModalGameView.as_view(), name='modal_game_view'),
    path('game/<slug:game_slug>', GameView.as_view() , name='game'),


    # path('genres/<slug:genre_slug/>', GamesListView.as_view(), name='genres')
    #path('tags/<slug:tag_slug>/', GamesListView.as_view(), name='tags'),

]

games/models.py
from django.db import models
from django.db.models import Avg

from users.models import User

# Возрастной ценз взят из Википедии
Russian_system_of_age_ratings = [
    ('Информационная продукция для детей, не достигших возраста шести лет', '0+'),
    ('Информационная продукция для детей, достигших возраста шести лет', '6+'),
    ('Информационная продукция для детей, достигших возраста двенадцати лет', '12+'),
    ('Информационная продукция для детей, достигших возраста шестнадцати лет', '16+'),
    ('Информация, запрещённая для распространения среди детей', '18+'),
]


class GameGenre(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/catalog/filter/?genre={self.slug}'

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Developer(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Имя')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Разработчик'
        verbose_name_plural = 'Разработчики'


class Publisher(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Имя')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'


class Tag(models.Model):
    """Класс модели тегов. У любого магазина игр есть поиск
        по тегам - то есть по ключевым словам"""
    name = models.CharField("Тег", max_length=50, unique=True)
    slug = models.SlugField("url", max_length=100, unique=True)

    def get_absolute_url(self):
        return f'/catalog/filter/?tag={self.slug}'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Game(models.Model):
    """Модель для создания игры """
    name = models.CharField(max_length=60, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name="URL")
    main_image = models.ImageField(default="image", verbose_name='Главная картинка')
    description = models.TextField(max_length=500, verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    genres = models.ManyToManyField(to=GameGenre, verbose_name='Жанр')
    tags = models.ManyToManyField(to=Tag, verbose_name='Теги', blank=True)
    developer = models.ForeignKey(to=Developer, on_delete=models.PROTECT,
                                  verbose_name='Разработчик')  # запрещает удалять пользователя, пока у него есть посты.
    publisher = models.ForeignKey(to=Publisher, on_delete=models.PROTECT,
                                  verbose_name='Издатель')
    release_date = models.DateField(verbose_name='Дата выхода')
    age_limit = models.CharField(max_length=70, choices=Russian_system_of_age_ratings, verbose_name='Возрастной ценз')
    ready = models.BooleanField(default=True, verbose_name='Готов?')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/catalog/game/{self.slug}'

    def average_rating(self):
        """Для получения среднего рейтинга игры -> aggregate возвращает словарь"""
        return Rating.objects.filter(game=self).aggregate(Avg("rating"))["rating__avg"] or 0

    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"


class Rating(models.Model):
    """Модель для создания рейтинга игры. Связываем пользователя и иргу"""
    user = models.ForeignKey(User, related_name='user_rating', on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name='overall_score', on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.game.name}: {self.rating}"


class GameImage(models.Model):
    """Модель для создания картинок игры. Удаляются вместе с игрой"""
    product = models.ForeignKey(
        Game,
        related_name="images",
        on_delete=models.CASCADE
    )
    image = models.ImageField("image")

games/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView
from Game_store_Django.settings import PAGE_SIZE

from common.views import CommonContextMixin
from games.models import Game, GameGenre, Tag


class IndexView(CommonContextMixin, ListView):
    template_name = 'games/index.html'
    title = 'Главная страница'
    model = Game

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data()
        # context['games_featured'] = Game.objects.filter()
        context['games_recently_released_slider'] = Game.objects.order_by("-id")[:3]
        context['games_recently_released_row'] = Game.objects.order_by("-id")[3:8]
        return context


class GameListView(CommonContextMixin, ListView):
    """Получение нефильтрованного(светлого) списка"""
    # https://morioh.com/p/13fad7aa6083
    model = Game
    # queryset = Game.objects.filter(ready=True)
    title = 'Каталог'
    template_name = 'games/catalog.html'
    paginate_by = PAGE_SIZE

    def get_queryset(self):
        queryset = super(GameListView, self).get_queryset()
        if 'genre' not in self.request.GET.keys() and 'tag' not in self.request.GET.keys():
            return queryset.distinct('pk').only('name', 'price', 'main_image', 'slug')
        elif 'tag' not in self.request.GET.keys():
            queryset = Game.objects.filter(Q(genres__slug__in=self.request.GET.getlist('genre')))
        if 'genre' not in self.request.GET.keys():
            queryset = Game.objects.filter(Q(tags__slug__in=self.request.GET.getlist('tag')))
        queryset = queryset.distinct('pk').only('name', 'price', 'main_image', 'slug')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GameListView, self).get_context_data()
        context['genres'] = GameGenre.objects.all().values('name', 'slug')
        context['tags'] = Tag.objects.all().values('name', 'slug')
        return context


class ModalGameView(DetailView):
    """Класс для ajax получение quickview по игры"""
    template_name = 'games/product-quick-view.html'
    slug_url_kwarg = 'game_slug'
    queryset = Game.objects.select_related('developer', 'publisher').prefetch_related('images')


class GameView(CommonContextMixin, DetailView):
    """Для отображения информации об определенной игре"""
    template_name = 'games/game.html'
    slug_url_kwarg = 'game_slug'
    model = Game
    queryset = Game.objects.select_related('developer', 'publisher'). \
        only('name', 'description',
             'release_date',
             'quantity',
             'price',
             'age_limit',
             'developer__name', 'publisher__name', 'main_image'
             ).prefetch_related('images')

    def get_object(self, queryset=None):
        self.title = self.kwargs.get('name')
        return super(GameView, self).get_object()

    def get_context_data(self, **kwargs):
        context = super(CommonContextMixin, self).get_context_data(**kwargs)
        context['title'] = self.object.name
        return context

    # Использование prefetch_related необходимо, чтобы дважды не обращаться в базу за фото(у нас там карусель)

# Create your views here.

games/templates/games/catalog.html
{% extends 'games/base.html' %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="container">
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Каталог</li>
                </ol>
            </nav>
            <div class="row">
                <div class="col-lg-9">
                    <nav class="toolbox">
                        <div class="toolbox-left">
                            <div class="toolbox-item toolbox-sort">
                                                                <div class="select-custom">
                                                                    <select name="orderby" class="form-control">
                                                                        <option value="popularity">По популярности</option>
                                                                        <option value="rating">По средним оценкам</option>
                                                                        <option value="date">По новизне</option>
                                                                        <option value="price-to-low">По цене, дешевые</option>
                                                                        <option value="price-to-high">По цене, дорогие</option>
                                                                    </select>
                                                                </div><!-- End .select-custom -->

                                <a href="#" class="sorter-btn" title="Set Ascending Direction"><span class="sr-only">Set Ascending Direction</span></a>
                            </div><!-- End .toolbox-item -->
                        </div><!-- End .toolbox-left -->
                    </nav>

                    <div class="row row-sm product-ajax-grid">
                        {% for game in object_list %}
                            <div class="col-6 col-md-4 col-xl-3">
                                <div class="product-default inner-quickview inner-icon">
                                    <figure>
                                        <a href="{{ game.get_absolute_url }}">

                                            <img src="{{ game.main_image.url }}" style="height: 200px;width:200px">
                                        </a>
                                        <div class="btn-icon-group">
                                            <button class="btn-icon btn-add-cart" data-toggle="modal"
                                                    data-target="#addCartModal"><i class="icon-bag"></i></button>
                                        </div>
                                        <a href="{% url 'games:modal_game_view' game.slug %}" class="btn-quickview"
                                           title="Quick View">Quick View</a>
                                    </figure>
                                    <div class="product-details">
                                        <h2 class="product-title">
                                            <a href="{{ game.get_absolute_url }}">{{ game.name }}</a>
                                        </h2>
                                        <div class="price-box">
                                            <span class="product-price">{{ game.price }}</span>
                                        </div><!-- End .price-box -->
                                    </div><!-- End .product-details -->
                                </div>
                            </div>
                        {% endfor %}
                    </div><!-- End .row -->
                    <form action="{% url 'api:get_games' %}" method="get" name="pagination">
                        <nav class="toolbox toolbox-pagination">
                            {% if is_paginated %}
                                <ul class="pagination">
                                    {% for page in paginator.page_range %}
                                        <li class="page-item">
                                            <button type="button" class="page-link" onclick="ajaxPagination.call(this, {{page}})"> {{ page }} </button>
                                        </li>
                                    {% endfor %}
                                </ul>
                                </nav>
                            {% endif %}
                    </form>

                </div><!-- End .col-lg-9 -->

                <aside class="sidebar-shop col-lg-3 order-lg-first">
                    <form action="{% url 'api:get_games' %}" method="get" name="filter">
                        <div class="sidebar-wrapper">

                            <div class="widget">
                                <h3 class="widget-title">
                                    <a data-toggle="collapse" href="#widget-body-2" role="button" aria-expanded="true"
                                       aria-controls="widget-body-2">Жанры</a>
                                </h3>

                                <div class="collapse show" id="widget-body-2">
                                    <div class="widget-body">
                                        <ul class="cat-list">
                                            {% for genre in genres %}
                                                <li>
                                                    <input type="checkbox" class="checked" name="genres"
                                                           value="{{ genre.slug }}">
                                                    <span>{{ genre.name }}</span>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div><!-- End .widget-body -->
                                </div><!-- End .collapse -->
                            </div><!-- End .widget -->

                            <div class="widget">
                                <h3 class="widget-title">
                                    <a data-toggle="collapse" href="#widget-body-4" role="button" aria-expanded="true"
                                       aria-controls="widget-body-4">Теги</a>
                                </h3>

                                <div class="collapse show" id="widget-body-4">
                                    <div class="widget-body">
                                        <ul class="cat-list">
                                            {% for tag in tags %}
                                                <li>
                                                    <input type="checkbox" class="checked" name="tags"
                                                           value="{{ tag.slug }}">
                                                    <span>{{ tag.name }}</span>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div><!-- End .widget-body -->
                                </div><!-- End .collapse -->
                            </div><!-- End .widget -->

                            <div class="widget">
                                <h3 class="widget-title">
                                    <a data-toggle="collapse" href="#widget-body-3" role="button" aria-expanded="true"
                                       aria-controls="widget-body-3">Цена</a>
                                </h3>

                                <div class="collapse show" id="widget-body-3">
                                    <div class="widget-body">
                                        <div class="price-slider-wrapper">
                                            <input type="range" name="price" class="price-slider" min="0" max="3000" value="1000"><!-- End #price-slider -->
                                        </div><!-- End .price-slider-wrapper -->

                                        <div class="filter-price-action">
                                            <div class="filter-price-text">
                                                Цена <= 1000 руб.
                                                <span ></span>
                                            </div><!-- End .filter-price-text -->
                                        </div><!-- End .filter-price-action -->

                                    </div><!-- End .widget-body -->
                                </div><!-- End .collapse -->
                                <br>
                                <button type="submit" class="btn btn-primary">Отфильтровать</button>
                            </div><!-- End .widget -->


                        </div><!-- End .sidebar-wrapper -->
                </aside>
                </form>
            </div><!-- End .row -->
        </div><!-- End .container -->
    </main><!-- End .main -->
{% endblock %}
{% block js_scripts %}
    <script src="{% static 'assets/js/nouislider.min.js' %}"></script>

    <script src="{% static 'assets/js/script.js' %}"></script>
    <script src="{% static 'assets/js/hogan-3.0.1.js' %}"></script>
{% endblock %}

games/templates/games/product-quick-view.html
<div class="product-single-container product-single-default product-quick-view container">
    <div class="row">
        <div class="col-lg-6 col-md-6 product-single-gallery">
            <div class="product-slider-container product-item">
                <div class="product-single-carousel owl-carousel owl-theme">
                    <div class="product-item">
                            <img class="product-single-image" src={{ game.main_image.url }}/>
                        </div>
                    {% for image in game.images.all %}
                        <div class="product-item">
                            <img class="product-single-image" src={{ image.image.url }}/>
                        </div>
                    {% endfor %}
                </div>
                <!-- End .product-single-carousel -->
            </div>

        </div><!-- End .col-lg-7 -->

        <div class="col-lg-6 col-md-6">
            <div class="product-single-details">
                <h1 class="product-title"></h1>

                <div class="ratings-container">
                    <div class="product-ratings">
                        <span class="ratings" style="width:60%">{{ game.average_rating }}</span><!-- End .ratings -->
                    </div><!-- End .product-ratings -->

                    <a href="#" class="rating-link">( 6 Reviews )</a>
                </div><!-- End .product-container -->

                <div class="price-box">
                    <span class="product-price">{{ game.price }} руб.</span>
                </div><!-- End .price-box -->

                <div class="product-desc">
                    <p>{{ game.description }}</p>
                </div><!-- End .product-desc -->


                <div class="product-action">
                    <div class="product-single-qty">
                        <input class="horizontal-quantity form-control" type="text">
                    </div><!-- End .product-single-qty -->

                    <a href="cart.html" class="paction add-cart" title="Add to Cart">
                        Add to Cart
                    </a>
                    <a href="#" class="paction add-wishlist" title="Add to Wishlist">
                        <span>Add to Wishlist</span>
                    </a>
                </div><!-- End .product-action -->

            </div><!-- End .product-single-details -->
        </div><!-- End .col-lg-5 -->
    </div><!-- End .row -->
</div><!-- End .product-single-container -->